apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  labels:
    app.uffizzi.com/envvar-override-key-0: UFFIZZI_URL
    # app.uffizzi.com/envvar-override-value-0: .default.ingress.backstage.rules[0].host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage-service-account
      containers:
        - name: backstage
          image: backstage/backstage
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
          env:
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: "postgres.default.svc.cluster.local"
