apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/backstage-deploy.yaml
- manifests/backstage-crb.yaml
- manifests/backstage-ingress.yaml
- manifests/backstage-sa.yaml
- manifests/backstage-secret.yaml
- manifests/backstage-svc.yaml
- manifests/pg-svc.yaml
- manifests/pg-deploy.yaml
- manifests/pg-secret.yaml
- manifests/pg-volume.yaml
